# Backward-compat re-export – implementation moved to service/schema/service.py
from core.extensions.tenant.schema.service import (  # noqa: F401
    PublicSchemaMigration,
    TenantSchemaHook,
    create_tenant_schema,
    drop_tenant_schema,
    install_schema_tables,
    list_missing_tenant_schema_tables,
    list_tenant_schema_hooks,
    list_tenant_schema_table_names,
    list_tenant_slugs,
    register_manifest_tenant_schema_hooks,
    register_tenant_schema_hooks,
    reset_tenant_schema_hooks,
    run_schema_statements,
    sync_existing_tenant_schemas,
    tenant_schema_exists,
    upgrade_public_schema,
    upgrade_tenant_schema,
)

__all__ = [
    "PublicSchemaMigration",
    "TenantSchemaHook",
    "create_tenant_schema",
    "drop_tenant_schema",
    "install_schema_tables",
    "list_missing_tenant_schema_tables",
    "list_tenant_schema_hooks",
    "list_tenant_schema_table_names",
    "list_tenant_slugs",
    "register_manifest_tenant_schema_hooks",
    "register_tenant_schema_hooks",
    "reset_tenant_schema_hooks",
    "run_schema_statements",
    "sync_existing_tenant_schemas",
    "tenant_schema_exists",
    "upgrade_public_schema",
    "upgrade_tenant_schema",
]
