from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any, Protocol

from apps.knowledge.domain.context_profile import ContextProfile
from apps.knowledge.domain.corpus import Corpus
from apps.knowledge.domain.claim import Claim
from apps.knowledge.domain.document import Document
from apps.knowledge.domain.ingest_event import IngestEvent
from apps.knowledge.domain.ingest_input import IngestInput
from apps.knowledge.domain.ingest_item import IngestItem
from apps.knowledge.domain.ingest_run import IngestRun
from apps.knowledge.domain.index_build import IndexBuild
from apps.knowledge.domain.index_profile import IndexProfile
from apps.knowledge.domain.interpretation_run import InterpretationRun
from apps.knowledge.domain.mention import Mention
from apps.knowledge.domain.paragraph import Paragraph
from apps.knowledge.domain.parser_run import ParserRun
from apps.knowledge.domain.query_run import QueryRun
from apps.knowledge.domain.retrieval_profile import RetrievalProfile
from apps.knowledge.domain.sentence import Sentence
from apps.knowledge.domain.sentence_interpretation import SentenceInterpretation
from apps.knowledge.domain.source import Source
from apps.knowledge.domain.space_time_frame import SpaceTimeFrame


class CorpusStorePort(Protocol):
    def list_all(self) -> list[Corpus]: ...
    def get_by_uuid(self, uuid: str) -> Corpus | None: ...
    def get_by_name(self, name: str) -> Corpus | None: ...
    def create(self, corpus: Corpus, *, actor_user_id: int) -> Corpus: ...
    def update(self, corpus: Corpus, *, actor_user_id: int) -> Corpus: ...
    def delete(self, uuid: str) -> None: ...
    def list_permissions(self, corpus_uuid: str) -> list[tuple[int, str]]: ...
    def list_permissions_batch(self, corpus_uuids: list[str]) -> dict[str, list[tuple[int, str]]]: ...
    def set_permissions(self, corpus_uuid: str, permissions: list[tuple[int, str]], *, actor_user_id: int) -> None: ...
    def get_kb_ids_with_permission(self, user_id: int, permission: str) -> list[int]: ...


class SourceStorePort(Protocol):
    def create(self, source: Source) -> Source: ...
    def list_for_corpus(self, corpus_uuid: str) -> list[Source]: ...
    def get(self, source_id: str) -> Source | None: ...
    def update(self, source: Source) -> Source: ...
    def delete(self, source_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class IndexProfileStorePort(Protocol):
    def get(self, key: str) -> IndexProfile | None: ...
    def list_all(self) -> list[IndexProfile]: ...


class IndexBuildStorePort(Protocol):
    def create(self, build: IndexBuild) -> IndexBuild: ...
    def update(self, build: IndexBuild) -> IndexBuild: ...
    def get(self, build_id: str) -> IndexBuild | None: ...
    def list_for_corpus(self, corpus_uuid: str) -> list[IndexBuild]: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class QueryRunStorePort(Protocol):
    def save(self, run: QueryRun) -> QueryRun: ...
    def list_recent(self, *, corpus_uuid: str | None = None, limit: int = 20) -> list[QueryRun]: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class IngestRunStorePort(Protocol):
    def create(self, run: IngestRun) -> IngestRun: ...
    def update(self, run: IngestRun) -> IngestRun: ...
    def get(self, run_id: str) -> IngestRun | None: ...
    def list_for_corpus(self, corpus_uuid: str, *, limit: int = 20) -> list[IngestRun]: ...
    def list_recent(self, *, limit: int = 20) -> list[IngestRun]: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class IngestItemStorePort(Protocol):
    def create_many(self, items: list[IngestItem]) -> list[IngestItem]: ...
    def update(self, item: IngestItem) -> IngestItem: ...
    def get(self, item_id: str) -> IngestItem | None: ...
    def list_for_run(self, run_id: str) -> list[IngestItem]: ...
    def find_by_hash(self, *, corpus_uuid: str, content_hash: str, exclude_item_id: str | None = None) -> IngestItem | None: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class IngestInputStorePort(Protocol):
    def create_many(self, inputs: list[IngestInput]) -> list[IngestInput]: ...
    def get_for_item(self, item_id: str) -> IngestInput | None: ...
    def list_file_objects_for_corpus(self, corpus_uuid: str) -> list[tuple[str, str]]: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class IngestEventStorePort(Protocol):
    def create(self, event: IngestEvent) -> IngestEvent: ...
    def list_for_run(self, run_id: str) -> list[IngestEvent]: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class ParserRunStorePort(Protocol):
    def create(self, run: ParserRun) -> ParserRun: ...
    def update(self, run: ParserRun) -> ParserRun: ...
    def get(self, run_id: str) -> ParserRun | None: ...
    def get_for_source(self, source_id: str) -> ParserRun | None: ...
    def list_for_corpus(self, corpus_uuid: str, *, limit: int = 50) -> list[ParserRun]: ...
    def delete_for_source(self, source_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class DocumentStorePort(Protocol):
    def create(self, document: Document) -> Document: ...
    def update(self, document: Document) -> Document: ...
    def get(self, document_id: str) -> Document | None: ...
    def get_for_source(self, source_id: str) -> Document | None: ...
    def delete_for_source(self, source_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class ParagraphStorePort(Protocol):
    def create_many(self, paragraphs: list[Paragraph]) -> list[Paragraph]: ...
    def list_for_document(self, document_id: str) -> list[Paragraph]: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class SentenceStorePort(Protocol):
    def create_many(self, sentences: list[Sentence]) -> list[Sentence]: ...
    def get(self, sentence_id: str) -> Sentence | None: ...
    def list_for_document(self, document_id: str) -> list[Sentence]: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class InterpretationRunStorePort(Protocol):
    def create(self, run: InterpretationRun) -> InterpretationRun: ...
    def update(self, run: InterpretationRun) -> InterpretationRun: ...
    def get_for_document(self, document_id: str) -> InterpretationRun | None: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class SentenceInterpretationStorePort(Protocol):
    def create_many(self, items: list[SentenceInterpretation]) -> list[SentenceInterpretation]: ...
    def get_for_sentence(self, sentence_id: str) -> SentenceInterpretation | None: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class MentionStorePort(Protocol):
    def create_many(self, items: list[Mention]) -> list[Mention]: ...
    def list_for_sentence(self, sentence_id: str) -> list[Mention]: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class ClaimStorePort(Protocol):
    def create_many(self, items: list[Claim]) -> list[Claim]: ...
    def list_for_sentence(self, sentence_id: str) -> list[Claim]: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class SpaceTimeFrameStorePort(Protocol):
    def create_many(self, items: list[SpaceTimeFrame]) -> list[SpaceTimeFrame]: ...
    def list_for_sentence(self, sentence_id: str) -> list[SpaceTimeFrame]: ...
    def list_for_claim_ids(self, claim_ids: list[str]) -> list[SpaceTimeFrame]: ...
    def delete_for_document(self, document_id: str) -> int: ...
    def delete_for_corpus(self, corpus_uuid: str) -> int: ...


class ChunkBuilderPort(Protocol):
    def build_chunks(self, text: str) -> list[str]: ...


class EmbeddingEnginePort(Protocol):
    async def embed_text(self, text: str) -> list[float]: ...


class VectorIndexPort(Protocol):
    async def ensure_collection_schema_async(self, collection_name: str, vector_size: int | None = None) -> None: ...
    async def upsert_sentence_points(self, collection: str, rows: list[dict[str, Any]]) -> None: ...
    def delete_collection(self, name: str) -> None: ...
    async def search_points(
        self,
        collection: str,
        query: str | None = None,
        limit: int = 10,
        point_types: list[str] | None = None,
        payload_filter: dict[str, Any] | None = None,
        query_vector: list[float] | None = None,
        lexical_query: str | None = None,
        fusion_semantic_weight: float | None = None,
        fusion_lexical_weight: float | None = None,
        lexical_focus_terms: list[str] | None = None,
        exact_phrases: list[str] | None = None,
        rare_terms: list[str] | None = None,
    ) -> list[dict[str, Any]]: ...


class RetrievalEnginePort(Protocol):
    async def retrieve(
        self,
        *,
        query: str,
        builds: list[IndexBuild],
        retrieval_profile: RetrievalProfile,
    ) -> list[dict[str, Any]]: ...


class ContextBuilderPort(Protocol):
    def build_context(
        self,
        *,
        query: str,
        hits: list[dict[str, Any]],
        context_profile: ContextProfile,
        query_run_id: str,
    ) -> tuple[str, list[dict[str, Any]]]: ...


class MetricsStorePort(Protocol):
    def increment(self, metric: str, value: int = 1) -> None: ...
    def record_timing(self, metric: str, value_ms: float) -> None: ...
    def snapshot(self) -> dict[str, object]: ...


class KnowledgeFacadePort(Protocol):
    def list_all(self, current_user_id: int | None = None, current_user: Any | None = None) -> list[Corpus]: ...
    def list_all_unfiltered(self) -> list[Corpus]: ...
    def create(
        self,
        name: str,
        description: str | None = None,
        permissions: list[tuple[int, str]] | None = None,
        current_user_id: int | None = None,
    ) -> Corpus: ...
    def update(
        self,
        uuid: str,
        name: str,
        description: str | None,
        personal_data_mode: str | None = None,
        current_user_id: int | None = None,
    ) -> Corpus: ...
    def delete(self, uuid: str, confirm_name: str | None = None, demo_mode: bool = False) -> None: ...
    def clear_contents(
        self,
        uuid: str,
        *,
        confirm_name: str | None = None,
        current_user_id: int | None = None,
    ) -> dict[str, int]: ...
    def user_can_use(self, kb_uuid: str, user_id: int, user: Any | None) -> bool: ...
    def user_can_train(self, kb_uuid: str, user_id: int, user: Any | None) -> bool: ...
    def get_trainable_kb_ids(self, user_id: int, user: Any | None) -> set[int]: ...
    def get_permissions_with_users(self, kb_uuid: str) -> list[dict[str, Any]]: ...
    def get_permissions_with_users_batch(self, kb_uuids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def set_permissions(
        self,
        kb_uuid: str,
        permissions: list[tuple[int, str]],
        current_user_id: int | None = None,
    ) -> None: ...
    def qdrant_collection_for_uuid(self, kb_uuid: str) -> str | None: ...
    def create_source(self, *, tenant: str, corpus_uuid: str, title: str, source_type: str, raw_content: str | None, file_ref: str | None, created_by: int | None) -> Source: ...
    def list_sources(self, corpus_uuid: str) -> list[Source]: ...
    def schedule_index_build(self, *, tenant: str, corpus_uuid: str, index_profile_key: str, created_by: int | None) -> IndexBuild: ...
    async def run_index_build(self, build_id: str) -> IndexBuild: ...
    def get_index_build(self, build_id: str) -> IndexBuild | None: ...
    def create_text_ingest_run(self, *, tenant: str, corpus_uuid: str, title: str, text: str, created_by: int | None) -> IngestRun: ...
    def create_file_ingest_run(self, *, tenant: str, corpus_uuid: str, files: list[dict[str, Any]], created_by: int | None) -> IngestRun: ...
    def create_url_ingest_run(self, *, tenant: str, corpus_uuid: str, urls: list[dict[str, Any]], created_by: int | None) -> IngestRun: ...
    def process_ingest_run(self, run_id: str) -> IngestRun: ...
    def request_ingest_item_reprocess(self, item_id: str, *, current_user_id: int | None = None) -> IngestRun: ...
    def process_ingest_item(self, item_id: str) -> IngestRun: ...
    def get_ingest_run(self, run_id: str) -> IngestRun | None: ...
    def list_ingest_runs(self, corpus_uuid: str, *, limit: int = 20) -> list[IngestRun]: ...
    def get_ingest_item(self, item_id: str) -> IngestItem | None: ...
    def get_ingest_input_for_item(self, item_id: str) -> IngestInput | None: ...
    def read_ingest_file_bytes(self, item_id: str) -> tuple[bytes, str | None, str | None]: ...
    def list_ingest_items(self, run_id: str) -> list[IngestItem]: ...
    def list_ingest_events(self, run_id: str) -> list[IngestEvent]: ...
    def parse_source(
        self,
        source_id: str,
        *,
        created_by: int | None = None,
        progress_callback: Callable[[str, dict[str, Any]], None] | None = None,
    ) -> ParserRun: ...
    def get_document_for_ingest_item(self, item_id: str) -> Document | None: ...
    def list_paragraphs_for_ingest_item(self, item_id: str) -> list[Paragraph]: ...
    def list_sentences_for_ingest_item(self, item_id: str) -> list[Sentence]: ...
    def get_sentence_interpretation(self, sentence_id: str) -> dict[str, Any] | None: ...
    async def retrieve(
        self,
        *,
        tenant: str,
        corpus_uuid: str,
        query: str,
        build_ids: list[str] | None = None,
        retrieval_profile: RetrievalProfile | None = None,
        context_profile: ContextProfile | None = None,
        compare_mode: bool = False,
    ) -> QueryRun: ...
    async def build_chat_context(
        self,
        *,
        tenant: str,
        corpus_uuid: str,
        query: str,
        build_ids: list[str] | None = None,
        retrieval_profile: RetrievalProfile | None = None,
        context_profile: ContextProfile | None = None,
    ) -> dict[str, Any]: ...
    def get_metrics(self) -> dict[str, object]: ...


VectorIndexFactory = Callable[[], VectorIndexPort]
EmbeddingEngineFactory = Callable[[], EmbeddingEnginePort]
BackgroundBuildRunner = Callable[[str], Awaitable[IndexBuild]]


__all__ = [
    "BackgroundBuildRunner",
    "ClaimStorePort",
    "ChunkBuilderPort",
    "ContextBuilderPort",
    "CorpusStorePort",
    "DocumentStorePort",
    "EmbeddingEngineFactory",
    "EmbeddingEnginePort",
    "IngestEventStorePort",
    "IngestInputStorePort",
    "IngestItemStorePort",
    "IngestRunStorePort",
    "IndexBuildStorePort",
    "IndexProfileStorePort",
    "InterpretationRunStorePort",
    "KnowledgeFacadePort",
    "MentionStorePort",
    "MetricsStorePort",
    "ParagraphStorePort",
    "ParserRunStorePort",
    "QueryRunStorePort",
    "RetrievalEnginePort",
    "SpaceTimeFrameStorePort",
    "SentenceInterpretationStorePort",
    "SentenceStorePort",
    "SourceStorePort",
    "VectorIndexFactory",
    "VectorIndexPort",
]
