# Ez a fájl az adott terület adatmodelljeit és kapcsolódó struktúráit tartalmazza.
PERSONAL_DATA_MODE_NO = 'no_personal_data'
PERSONAL_DATA_MODE_CONFIRM = 'with_confirmation'
PERSONAL_DATA_MODE_ALLOWED = 'allowed_not_to_ai'
PERSONAL_DATA_MODE_DISABLED = 'no_pii_filter'

PERSONAL_DATA_SENSITIVITY_WEAK = 'weak'
PERSONAL_DATA_SENSITIVITY_MEDIUM = 'medium'
PERSONAL_DATA_SENSITIVITY_STRONG = 'strong'

__all__ = [
    'PERSONAL_DATA_MODE_NO',
    'PERSONAL_DATA_MODE_CONFIRM',
    'PERSONAL_DATA_MODE_ALLOWED',
    'PERSONAL_DATA_MODE_DISABLED',
    'PERSONAL_DATA_SENSITIVITY_WEAK',
    'PERSONAL_DATA_SENSITIVITY_MEDIUM',
    'PERSONAL_DATA_SENSITIVITY_STRONG',
]
