from __future__ import annotations

from enum import Enum


class IndexingErrorCode(str, Enum):
    EMBEDDING_JOB_NOT_FOUND = "EMBEDDING_JOB_NOT_FOUND"
    EMBEDDING_NOT_READY = "EMBEDDING_NOT_READY"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"
    NO_EMBEDDINGS_FOR_INDEXING = "NO_EMBEDDINGS_FOR_INDEXING"
    QDRANT_COLLECTION_MISSING = "QDRANT_COLLECTION_MISSING"
    QDRANT_DIMENSION_MISMATCH = "QDRANT_DIMENSION_MISMATCH"
    QDRANT_UPSERT_FAILED = "QDRANT_UPSERT_FAILED"
    INDEX_PAYLOAD_BUILD_FAILED = "INDEX_PAYLOAD_BUILD_FAILED"
    MISSING_EMBEDDING = "MISSING_EMBEDDING"
    INDEXING_PARTIAL_FAILURE = "INDEXING_PARTIAL_FAILURE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


__all__ = ["IndexingErrorCode"]
