from __future__ import annotations

from apps.contracts.conventions import (
    APP_MODULE_OPTIONAL_PATHS,
    APP_MODULE_RECOMMENDED_PATHS,
    APP_MODULE_REQUIRED_PATHS,
    module_hook_name,
    module_key,
    module_route_tag,
)
from apps.contracts.public_api import (
    APP_PLATFORM_SUPPORT_DIRECTORIES,
    PUBLIC_CORE_API_PREFIXES,
    PUBLIC_SHARED_APPS_PREFIXES,
)
from apps.contracts.service_keys import (
    MODULE_CHAT_LLM_CLIENT_FACTORY,
    MODULE_CHAT_SERVICE,
    MODULE_DEMO_SERVICE,
    MODULE_KNOWLEDGE_EMBEDDING_SERVICE_FACTORY,
    MODULE_KNOWLEDGE_QDRANT_FACTORY,
    MODULE_KNOWLEDGE_REPOSITORY,
    MODULE_KNOWLEDGE_SERVICE,
    MODULE_ORDERS_SERVICE,
    MODULE_PACKAGES_SERVICE,
    MODULE_PROFILE_SERVICE,
    MODULE_SETTINGS_SERVICE,
    MODULE_TRAFFIC_SERVICE,
    module_service_key,
)

__all__ = [
    "APP_MODULE_OPTIONAL_PATHS",
    "APP_MODULE_RECOMMENDED_PATHS",
    "APP_MODULE_REQUIRED_PATHS",
    "APP_PLATFORM_SUPPORT_DIRECTORIES",
    "MODULE_CHAT_LLM_CLIENT_FACTORY",
    "MODULE_CHAT_SERVICE",
    "MODULE_DEMO_SERVICE",
    "MODULE_KNOWLEDGE_EMBEDDING_SERVICE_FACTORY",
    "MODULE_KNOWLEDGE_QDRANT_FACTORY",
    "MODULE_KNOWLEDGE_REPOSITORY",
    "MODULE_KNOWLEDGE_SERVICE",
    "MODULE_ORDERS_SERVICE",
    "MODULE_PACKAGES_SERVICE",
    "MODULE_PROFILE_SERVICE",
    "MODULE_SETTINGS_SERVICE",
    "MODULE_TRAFFIC_SERVICE",
    "PUBLIC_CORE_API_PREFIXES",
    "PUBLIC_SHARED_APPS_PREFIXES",
    "module_hook_name",
    "module_key",
    "module_route_tag",
    "module_service_key",
]
