from __future__ import annotations

from enum import Enum


class ProcessingEventType(str, Enum):
    EXTRACT_STARTED = "EXTRACT_STARTED"
    EXTRACT_COMPLETED = "EXTRACT_COMPLETED"
    NORMALIZE_STARTED = "NORMALIZE_STARTED"
    NORMALIZE_COMPLETED = "NORMALIZE_COMPLETED"
    CHUNKING_STARTED = "CHUNKING_STARTED"
    CHUNKING_COMPLETED = "CHUNKING_COMPLETED"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    STEP_STARTED = "STEP_STARTED"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_FAILED = "STEP_FAILED"
    STEP_SKIPPED = "STEP_SKIPPED"


__all__ = ["ProcessingEventType"]
