from __future__ import annotations

from enum import Enum


class ProcessingIssueCode(str, Enum):
    OCR_EMPTY = "OCR_EMPTY"
    OCR_FAILED = "OCR_FAILED"
    PDF_PARSE_FAILED = "PDF_PARSE_FAILED"
    DOCX_PARSE_FAILED = "DOCX_PARSE_FAILED"
    NORMALIZE_PART_FAILED = "NORMALIZE_PART_FAILED"
    LOW_NORMALIZED_PART_COUNT = "LOW_NORMALIZED_PART_COUNT"
    CHUNK_VALIDATION_WARNING = "CHUNK_VALIDATION_WARNING"
    LOW_CHUNK_COUNT = "LOW_CHUNK_COUNT"
    NO_USABLE_PARTS = "NO_USABLE_PARTS"
    NO_CHUNKS_CREATED = "NO_CHUNKS_CREATED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    JOB_STUCK = "JOB_STUCK"
    DISCOVERY_FAILED = "DISCOVERY_FAILED"
    INDEXING_FAILED = "INDEXING_FAILED"
    INVALID_ENTITY_DICTIONARY_TYPE = "INVALID_ENTITY_DICTIONARY_TYPE"
    MISSING_CHUNK_LANGUAGE_FOR_ENRICHMENT = "MISSING_CHUNK_LANGUAGE_FOR_ENRICHMENT"
    NO_KEYWORDS_EXTRACTED = "NO_KEYWORDS_EXTRACTED"
    NO_TOPICS_DETECTED = "NO_TOPICS_DETECTED"
    LOW_ENRICHMENT_CONFIDENCE = "LOW_ENRICHMENT_CONFIDENCE"
    CONTENT_TYPE_UNKNOWN = "CONTENT_TYPE_UNKNOWN"
    ENRICHMENT_FAILED = "ENRICHMENT_FAILED"
    HIGH_UNKNOWN_CONTENT_TYPE_RATIO = "HIGH_UNKNOWN_CONTENT_TYPE_RATIO"
    LOW_TOPIC_COVERAGE = "LOW_TOPIC_COVERAGE"
    MISSING_CHUNK_LANGUAGE = "MISSING_CHUNK_LANGUAGE"
    MISSING_ENRICHMENT = "MISSING_ENRICHMENT"
    MISSING_SCORE = "MISSING_SCORE"
    DUPLICATE_KEYWORDS = "DUPLICATE_KEYWORDS"
    DUPLICATE_TOPICS = "DUPLICATE_TOPICS"
    MISSING_ENTITY_RELATIONSHIPS = "MISSING_ENTITY_RELATIONSHIPS"
    MISSING_TOPIC_RELATIONSHIPS = "MISSING_TOPIC_RELATIONSHIPS"
    MISSING_TEMPORAL_RELATIONSHIPS = "MISSING_TEMPORAL_RELATIONSHIPS"
    MISSING_SPATIAL_RELATIONSHIPS = "MISSING_SPATIAL_RELATIONSHIPS"
    MISSING_PROCESS_RELATIONSHIPS = "MISSING_PROCESS_RELATIONSHIPS"
    PROCESS_CONTENT_WITHOUT_PROCESS_EXTRACTION = "PROCESS_CONTENT_WITHOUT_PROCESS_EXTRACTION"
    LOW_KEYWORD_COVERAGE = "LOW_KEYWORD_COVERAGE"
    LOW_DISCOVERY_SCORE = "LOW_DISCOVERY_SCORE"
    MISSING_TEMPORAL_REFERENCE_DATE = "MISSING_TEMPORAL_REFERENCE_DATE"


__all__ = ["ProcessingIssueCode"]
