from __future__ import annotations

from enum import Enum


class ProcessingIssueCode(str, Enum):
    OCR_EMPTY = "OCR_EMPTY"
    OCR_FAILED = "OCR_FAILED"
    PDF_PARSE_FAILED = "PDF_PARSE_FAILED"
    DOCX_PARSE_FAILED = "DOCX_PARSE_FAILED"
    NORMALIZE_PART_FAILED = "NORMALIZE_PART_FAILED"
    LOW_NORMALIZED_PART_COUNT = "LOW_NORMALIZED_PART_COUNT"
    CHUNK_VALIDATION_WARNING = "CHUNK_VALIDATION_WARNING"
    LOW_CHUNK_COUNT = "LOW_CHUNK_COUNT"
    NO_USABLE_PARTS = "NO_USABLE_PARTS"
    NO_CHUNKS_CREATED = "NO_CHUNKS_CREATED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    JOB_STUCK = "JOB_STUCK"
    DISCOVERY_FAILED = "DISCOVERY_FAILED"
    INDEXING_FAILED = "INDEXING_FAILED"


__all__ = ["ProcessingIssueCode"]
