from __future__ import annotations

from enum import Enum


class ProcessingEventType(str, Enum):
    EXTRACT_STARTED = "EXTRACT_STARTED"
    EXTRACT_COMPLETED = "EXTRACT_COMPLETED"
    NORMALIZE_STARTED = "NORMALIZE_STARTED"
    NORMALIZE_COMPLETED = "NORMALIZE_COMPLETED"
    CHUNKING_STARTED = "CHUNKING_STARTED"
    CHUNKING_COMPLETED = "CHUNKING_COMPLETED"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    DISCOVERY_STARTED = "DISCOVERY_STARTED"
    LANGUAGE_DETECTION_STARTED = "LANGUAGE_DETECTION_STARTED"
    LANGUAGE_DETECTION_COMPLETED = "LANGUAGE_DETECTION_COMPLETED"
    ENTITY_EXTRACTION_STARTED = "ENTITY_EXTRACTION_STARTED"
    ENTITY_EXTRACTION_COMPLETED = "ENTITY_EXTRACTION_COMPLETED"
    LOCAL_ENRICHMENT_STARTED = "LOCAL_ENRICHMENT_STARTED"
    LOCAL_ENRICHMENT_COMPLETED = "LOCAL_ENRICHMENT_COMPLETED"
    TEMPORAL_EXTRACTION_STARTED = "TEMPORAL_EXTRACTION_STARTED"
    TEMPORAL_EXTRACTION_COMPLETED = "TEMPORAL_EXTRACTION_COMPLETED"
    SPATIAL_EXTRACTION_STARTED = "SPATIAL_EXTRACTION_STARTED"
    SPATIAL_EXTRACTION_COMPLETED = "SPATIAL_EXTRACTION_COMPLETED"
    PROCESS_EXTRACTION_STARTED = "PROCESS_EXTRACTION_STARTED"
    PROCESS_EXTRACTION_COMPLETED = "PROCESS_EXTRACTION_COMPLETED"
    RELATIONSHIP_BUILD_STARTED = "RELATIONSHIP_BUILD_STARTED"
    RELATIONSHIP_BUILD_COMPLETED = "RELATIONSHIP_BUILD_COMPLETED"
    KNOWLEDGE_SCORING_STARTED = "KNOWLEDGE_SCORING_STARTED"
    KNOWLEDGE_SCORING_COMPLETED = "KNOWLEDGE_SCORING_COMPLETED"
    DISCOVERY_VALIDATION_STARTED = "DISCOVERY_VALIDATION_STARTED"
    DISCOVERY_VALIDATION_COMPLETED = "DISCOVERY_VALIDATION_COMPLETED"
    DISCOVERY_READY_FOR_EMBEDDING = "DISCOVERY_READY_FOR_EMBEDDING"
    DISCOVERY_COMPLETED = "DISCOVERY_COMPLETED"
    DISCOVERY_FAILED = "DISCOVERY_FAILED"
    STEP_STARTED = "STEP_STARTED"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_FAILED = "STEP_FAILED"
    STEP_SKIPPED = "STEP_SKIPPED"


__all__ = ["ProcessingEventType"]
